### PR TITLE
Fixing weird source issue...

### PR DESCRIPTION
**Pull request by loganlearner**
TESTED LOCALLY ✅

### CODE REVIEW

**Comment by legokidlogan** [comment]
SetNoDraw on server causes the entity to not get networked, this is something that should be done on client.

**Review by wrefgtzweve — APPROVED** [review]
Shown in screenshare that it , looks good to me!

**Comment by loganlearner** [comment]
To be fair, it's already unreliable. Half the time I use this thing it doesn't work.

**Comment by legokidlogan** [comment]
No, it's just a precautionary concern. If an entity no longer gets networked, then we might run into issues when we try to make the client do things with it. We'd have to do extensive testing to see if it does end up causing an issue in reality, which it may or may not.

**Review by brandonsturgeon — APPROVED** [review]

**Pull request merged**
