### PR TITLE
Fix-jumpy-seat

### PR DESCRIPTION
**Pull request by wrefgtzweve**

### CODE REVIEW

**Comment by legokidlogan** [comment]
Sometimes people attach things to their lfs plane, such as guns or bombs, the trace should filter out ents that are connected to the plane

**Comment by wrefgtzweve** [comment]
however connects stuff under their plane is a dumbass and deserves to plummet to their death

**Review by brandonsturgeon — CHANGES_REQUESTED** [review]
Just throw a quick https://wiki.facepunch.com/gmod/duplicator.GetAllConstrainedEntitiesAndConstraints in there, it'll only be a couple of extra lines

**Review by brandonsturgeon — APPROVED** [review]
Meant to make that an approval

**Pull request merged**
