### PR TITLE
Don't break when mixpanel doesn't exist

### PR DESCRIPTION
**Pull request by legokidlogan**

### CODE REVIEW

**Comment by legokidlogan** [comment]
`pcall()` also stops the error, while the original `ProtectedCall()` does not, and it avoids the need for using a `file.Exists()` check. It's what PCL recommended.

**Comment by wrefgtzweve** [comment]
It doesn't

**Comment by legokidlogan** [comment]
Still using a `pcall()` inside for in case mixpanel errors for some *other* reason (even though it really never will)

**Comment by wrefgtzweve** [comment]
Won't really change anything, there's no reason require ever throws an halting error, maybe only if you give it the wrong variable type.

**Pull request merged**
